package telemetry

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

var (
	uuidRegex    = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)
	jwtRegex     = regexp.MustCompile(`eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+`)
	ageKeyRegex  = regexp.MustCompile(`AGE-SECRET-KEY-[0-9A-Z]{59}`)
)

var forbiddenSubstrings = []string{
	"AGE-SECRET-KEY-",
	"Cf-Access-Jwt-Assertion",
	"cf_clearance",
	"acb_session",
	"acb_jwt",
	"<!DOCTYPE html",
	"<html",
	"<body",
	"<table",
}

// ValidateNoSecrets verifies that the given telemetry payload does not contain
// secret credentials, tokens, raw ACB HTML, or high-cardinality identifiers in global keys.
func ValidateNoSecrets(payload any) error {
	raw, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("json marshal payload: %w", err)
	}
	content := string(raw)
	// Unescape HTML unicode sequences generated by json.Marshal
	content = strings.ReplaceAll(content, "\\u003c", "<")
	content = strings.ReplaceAll(content, "\\u003e", ">")
	content = strings.ReplaceAll(content, "\\u0026", "&")

	// Check forbidden substrings
	for _, sub := range forbiddenSubstrings {
		if strings.Contains(strings.ToLower(content), strings.ToLower(sub)) {
			return fmt.Errorf("telemetry payload contains forbidden secret/markup pattern: %q", sub)
		}
	}

	// Check JWT regex
	if jwtRegex.MatchString(content) {
		return errors.New("telemetry payload contains JSON Web Token (JWT)")
	}

	// Check age secret key regex
	if ageKeyRegex.MatchString(content) {
		return errors.New("telemetry payload contains age secret key")
	}

	// Check for raw unmasked Bearer tokens
	if strings.Contains(content, "Bearer ") {
		return errors.New("telemetry payload contains raw Bearer token")
	}

	// Check map keys for high-cardinality UUIDs
	var decoded any
	if err := json.Unmarshal(raw, &decoded); err == nil {
		if err := checkCardinality(decoded); err != nil {
			return err
		}
	}

	return nil
}

func checkCardinality(node any) error {
	switch v := node.(type) {
	case map[string]any:
		for k, val := range v {
			if uuidRegex.MatchString(k) {
				return fmt.Errorf("high-cardinality UUID used as telemetry key: %q", k)
			}
			if err := checkCardinality(val); err != nil {
				return err
			}
		}
	case []any:
		for _, elem := range v {
			if err := checkCardinality(elem); err != nil {
				return err
			}
		}
	}
	return nil
}
