#!/usr/bin/env bash
# Canonical runtime state layout. Defines all shared mutable runtime paths.
set -Eeuo pipefail

RUNTIME_ROOT="${RUNTIME_ROOT:-${DEPLOY_PATH:-/opt/acb-transaction-webhook}}"
RUNTIME_DEPLOY_DIR="$RUNTIME_ROOT/deploy"
RUNTIME_STATE_DIR="$RUNTIME_ROOT/state"
RUNTIME_DATA_DIR="$RUNTIME_ROOT/data"
RUNTIME_RELEASES_DIR="$RUNTIME_ROOT/releases"

ENV_FILE="$RUNTIME_DEPLOY_DIR/.env.production"
RELEASE_ENV_FILE="$RUNTIME_DEPLOY_DIR/.release.env"
SECRETS_DIR="$RUNTIME_DEPLOY_DIR/secrets"
BACKUP_DIR="${BACKUP_DIR:-/var/backups/acb}"
CURRENT_RELEASE_FILE="$RUNTIME_STATE_DIR/current-release.json"
TX_JOURNAL_FILE="$RUNTIME_DATA_DIR/deploy-journal.json"
ROLLOUT_JOURNAL_FILE="$RUNTIME_DATA_DIR/rollout-journal.json"
ACTIVE_SLOT_FILE="$RUNTIME_STATE_DIR/gateway-active-slot"
PREVIOUS_SLOT_FILE="$RUNTIME_STATE_DIR/gateway-previous-slot"
FRONTEND_ACTIVE_SLOT_FILE="$RUNTIME_STATE_DIR/frontend-active-slot"
FRONTEND_PREVIOUS_SLOT_FILE="$RUNTIME_STATE_DIR/frontend-previous-slot"
DEPLOY_STATE_FILE="$RUNTIME_STATE_DIR/deploy-state.json"
SOAK_STATE_FILE="$RUNTIME_STATE_DIR/soak-state.env"
MIGRATION_RECORD="$RUNTIME_DATA_DIR/migration-record.json"
PENDING_GATEWAY_RETIRE_FILE="$RUNTIME_DATA_DIR/pending-gateway-retire.env"
PENDING_FRONTEND_RETIRE_FILE="$RUNTIME_DATA_DIR/pending-frontend-retire.env"

export RUNTIME_ROOT RUNTIME_DEPLOY_DIR RUNTIME_STATE_DIR RUNTIME_DATA_DIR RUNTIME_RELEASES_DIR
export ENV_FILE RELEASE_ENV_FILE SECRETS_DIR BACKUP_DIR CURRENT_RELEASE_FILE TX_JOURNAL_FILE ROLLOUT_JOURNAL_FILE
export ACTIVE_SLOT_FILE PREVIOUS_SLOT_FILE FRONTEND_ACTIVE_SLOT_FILE FRONTEND_PREVIOUS_SLOT_FILE
export DEPLOY_STATE_FILE SOAK_STATE_FILE MIGRATION_RECORD PENDING_GATEWAY_RETIRE_FILE PENDING_FRONTEND_RETIRE_FILE
