name: acb

volumes:
  gateway_data:
    external: true
    name: ${DATA_VOLUME_NAME:-bank-event-gateway_gateway_data}
  bark_data:
    external: true
    name: ${BARK_VOLUME_NAME:-bank-event-gateway_bark_data}

networks:
  edge-acb:
    external: true
    name: edge-acb
  acb-core:
    external: true
    name: acb-core
  acb-egress:
    external: true
    name: acb-egress
  none:
    internal: true

secrets:
  app_master_key:
    file: ./secrets/app_master_key
  tts_internal_token:
    file: ./secrets/tts_internal_token
  worker_internal_token:
    file: ./secrets/worker_internal_token
  bark_basic_auth_user:
    file: ./secrets/bark_basic_auth_user
  bark_basic_auth_password:
    file: ./secrets/bark_basic_auth_password
